# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f184be64080932515895a39d9719e78efef63b480509fd4de45170ff0105199a55d6e843241569f0acd9ad9d67de562cbbbd0c99fb4a4c72aa3250fbcbc45074

test:
  secret_key_base: a0a458bf2276902607bf083fa10c00906d6709e60529732f7f24d1b0828f824021a7621ad572cb49264103db96807070981b088fec872d96b99788c4510ef4ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
